apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: myapp2-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: myapp2
  template:  
    metadata: # Dictionary
      name: myapp2-pod
      labels: # Dictionary
        app: myapp2  # Key value pairs
    spec:
      containers: # List
        - name: myapp2-container
          image: ghcr.io/stacksimplify/kube-nginxapp2:1.0.0
          ports: 
            - containerPort: 80  
          resources:
            requests:
              memory: "256Mi" # 128 MebiByte is equal to 135 Megabyte (MB)
              cpu: "250m" # `m` means milliCPU
            limits:
              memory: "512Mi"
              cpu: "400m"  # 1000m is equal to 1 VCPU core                                               
            